from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import AnalysisConfig
from .loader import load_financial_statements
from .metrics import build_analysis_summary, calculate_period_metrics
from .models import AnalysisSummary, FinancialStatementRecord, PeriodMetrics
from .reporting import write_markdown_report, write_summary_json
from .visualization import (
    generate_financial_position_chart,
    generate_profitability_chart,
)


@dataclass(frozen=True, slots=True)
class AnalysisArtifacts:
    records: list[FinancialStatementRecord]
    period_metrics: list[PeriodMetrics]
    summary: AnalysisSummary


def analyze_financial_statements(
    input_path: str | Path,
    *,
    company_name: str = "",
) -> AnalysisArtifacts:
    """
    Analyzes financial statements and generates an AnalysisArtifacts object with records, period metrics, and an analysis summary.

    Args:
        input_path (str | Path): Path to the CSV file containing the financial statements.
        company_name (str, optional): Company name to use in the analysis summary. Defaults to "".

    Returns:
        AnalysisArtifacts: An AnalysisArtifacts object containing the records, period metrics, and analysis summary.
    """
    # Load financial statements from the input CSV file
    records = load_financial_statements(input_path)

    # Calculate period metrics from the financial statements
    period_metrics = calculate_period_metrics(records)

    # Build the analysis summary from the period metrics
    summary = build_analysis_summary(period_metrics, company_name=company_name)

    # Return the analysis artifacts object
    return AnalysisArtifacts(
        records=records, period_metrics=period_metrics, summary=summary
    )


def run_analysis_pipeline(config: AnalysisConfig) -> AnalysisSummary:
    """
    Runs the financial analysis pipeline using the provided AnalysisConfig object.

    Loads financial statements from the input CSV file, analyzes the statements, and generates an AnalysisSummary object.
    Writes the AnalysisSummary object to the summary output path as JSON.
    Writes a Markdown report based on the AnalysisSummary object to the report output path.
    Generates a profitability trend chart based on the AnalysisSummary object and writes it to the profitability chart output path.
    Generates a financial position chart based on the AnalysisSummary object and writes it to the financial position chart output path.

    Args:
        config (AnalysisConfig): The AnalysisConfig object containing the pipeline configuration.

    Returns:
        AnalysisSummary: The AnalysisSummary object generated by the pipeline.
    """
    artifacts = analyze_financial_statements(
        config.input_path,
        company_name=config.company_name,
    )

    write_summary_json(artifacts.summary, config.summary_output)
    write_markdown_report(artifacts.summary, config.report_output)
    generate_profitability_chart(
        artifacts.period_metrics,
        config.profitability_chart_output,
        company_name=config.company_name,
    )
    generate_financial_position_chart(
        artifacts.period_metrics,
        config.financial_position_chart_output,
        company_name=config.company_name,
    )
    return artifacts.summary
