from __future__ import annotations

import html
from pathlib import Path

from .models import PeriodAnalysis


def generate_trend_chart(analyses: list[PeriodAnalysis], output_path: str | Path) -> None:
    if not analyses:
        raise ValueError("At least one analyzed period is required for chart generation.")

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    width = 1120
    height = 760
    periods = [analysis.period for analysis in analyses]

    svg_parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        "<style>",
        "text { font-family: Arial, sans-serif; fill: #102a43; }",
        ".title { font-size: 30px; font-weight: bold; }",
        ".subtitle { font-size: 14px; fill: #486581; }",
        ".panel-title { font-size: 18px; font-weight: bold; }",
        ".axis-label { font-size: 12px; fill: #627d98; }",
        ".legend { font-size: 12px; }",
        "</style>",
        '<rect width="100%" height="100%" fill="#f8fbff" />',
        '<text class="title" x="60" y="60">Company Financial Trends</text>',
        '<text class="subtitle" x="60" y="88">Structured CSV analysis output generated by the CLI.</text>',
    ]

    svg_parts.extend(
        _build_panel(
            x=50,
            y=120,
            width=1020,
            height=270,
            title="Revenue vs Net Income",
            periods=periods,
            series=[
                ("Revenue", [analysis.revenue for analysis in analyses], "#0f766e"),
                ("Net Income", [analysis.net_income for analysis in analyses], "#b45309"),
            ],
            y_formatter=lambda value: f"${value / 1_000_000:.1f}M",
        )
    )

    svg_parts.extend(
        _build_panel(
            x=50,
            y=430,
            width=1020,
            height=270,
            title="Margin Trend",
            periods=periods,
            series=[
                ("Gross Margin", [analysis.gross_margin * 100 for analysis in analyses], "#1d4ed8"),
                ("Operating Margin", [analysis.operating_margin * 100 for analysis in analyses], "#7c3aed"),
                ("Net Margin", [analysis.net_margin * 100 for analysis in analyses], "#be123c"),
            ],
            y_formatter=lambda value: f"{value:.0f}%",
        )
    )

    svg_parts.append("</svg>")
    path.write_text("\n".join(svg_parts), encoding="utf-8")


def _build_panel(
    *,
    x: int,
    y: int,
    width: int,
    height: int,
    title: str,
    periods: list[str],
    series: list[tuple[str, list[float], str]],
    y_formatter,
) -> list[str]:
    margin_top = 42
    margin_right = 35
    margin_bottom = 48
    margin_left = 80

    plot_left = x + margin_left
    plot_top = y + margin_top
    plot_width = width - margin_left - margin_right
    plot_height = height - margin_top - margin_bottom
    plot_bottom = plot_top + plot_height
    plot_right = plot_left + plot_width

    values = [value for _, data, _ in series for value in data]
    value_min = min(0.0, min(values))
    value_max = max(values)
    if value_max == value_min:
        value_max += 1

    parts = [
        f'<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="18" fill="#ffffff" stroke="#d9e2ec" />',
        f'<text class="panel-title" x="{x + 24}" y="{y + 28}">{html.escape(title)}</text>',
    ]

    for tick in range(5):
        ratio = tick / 4
        tick_value = value_max - ((value_max - value_min) * ratio)
        tick_y = plot_top + (plot_height * ratio)
        parts.append(
            f'<line x1="{plot_left}" y1="{tick_y:.2f}" x2="{plot_right}" y2="{tick_y:.2f}" stroke="#e4edf5" />'
        )
        parts.append(
            f'<text class="axis-label" x="{plot_left - 12}" y="{tick_y + 4:.2f}" text-anchor="end">{html.escape(y_formatter(tick_value))}</text>'
        )

    point_count = len(periods)
    if point_count == 1:
        x_positions = [plot_left + (plot_width / 2)]
    else:
        x_positions = [
            plot_left + (plot_width * index / (point_count - 1)) for index in range(point_count)
        ]

    for label, position in zip(periods, x_positions):
        parts.append(
            f'<text class="axis-label" x="{position:.2f}" y="{plot_bottom + 24}" text-anchor="middle">{html.escape(label)}</text>'
        )

    for index, (label, _, color) in enumerate(series):
        legend_x = x + 24 + (index * 180)
        legend_y = y + height - 16
        parts.append(
            f'<line x1="{legend_x}" y1="{legend_y}" x2="{legend_x + 26}" y2="{legend_y}" stroke="{color}" stroke-width="3" />'
        )
        parts.append(
            f'<text class="legend" x="{legend_x + 34}" y="{legend_y + 4}">{html.escape(label)}</text>'
        )

    for _, data, color in series:
        point_coordinates = [
            (
                x_positions[index],
                _scale_value(
                    value=data[index],
                    min_value=value_min,
                    max_value=value_max,
                    plot_top=plot_top,
                    plot_height=plot_height,
                ),
            )
            for index in range(point_count)
        ]
        point_string = " ".join(f"{point_x:.2f},{point_y:.2f}" for point_x, point_y in point_coordinates)
        parts.append(
            f'<polyline fill="none" stroke="{color}" stroke-width="3.5" points="{point_string}" />'
        )

        for point_x, point_y in point_coordinates:
            parts.append(
                f'<circle cx="{point_x:.2f}" cy="{point_y:.2f}" r="4.5" fill="{color}" stroke="#ffffff" stroke-width="2" />'
            )

    return parts


def _scale_value(
    *,
    value: float,
    min_value: float,
    max_value: float,
    plot_top: int,
    plot_height: int,
) -> float:
    ratio = (value - min_value) / (max_value - min_value)
    return plot_top + plot_height - (ratio * plot_height)
